POST http://localhost:8000/register/
content-type: application/json

{
    "email": "mafattah931@gmail.com",
    "name": "fattah",
    "password": "a1A@"
}

###

POST http://localhost:8000/login/password/
content-type: application/json

{
    "email": "youssef@getbrewsy.com",
    "password": "Sike_123"
}

###

POST http://localhost:8000/logout/
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhhbWFkYUBuZGFzc3NzLmNvbSIsImlhdCI6MTY1Mzg0MTI5NiwiZXhwIjoxNjU2NDMzMjk2fQ.7p2A6riD-aBMWf3GRDZnKyo-a3MeKzd02yEaj7bAjI4
